services:

  db:
    image: postgres:16
    container_name: excel_import_db
    restart: unless-stopped

    environment:
      POSTGRES_DB: excel_import_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


  redis:
    image: redis:7
    container_name: excel_import_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

      
volumes:                          # data will be saved even after container stopped 
  postgres_data: