"""create import errors table

Revision ID: ab9a0a831b19
Revises: 93a7c04d3cbe
Create Date: 2026-09-05 11:08:08.929873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab9a0a831b19'
down_revision: Union[str, Sequence[str], None] = '93a7c04d3cbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_job_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_errors_id'), 'import_errors', ['id'], unique=False)
    op.create_index(op.f('ix_import_errors_import_job_id'), 'import_errors', ['import_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_import_errors_import_job_id'), table_name='import_errors')
    op.drop_index(op.f('ix_import_errors_id'), table_name='import_errors')
    op.drop_table('import_errors')
    # ### end Alembic commands ###
